FROM ros:humble
 
# use bash
SHELL ["/bin/bash", "-c"]
 
# install utilities 
RUN apt update && apt upgrade -y && \
   apt install -y nano wget curl  

WORKDIR /root/home/

COPY zed2i.rviz ./zed2i.rviz
RUN apt update && apt install -y ros-humble-desktop-full
RUN apt-get install --no-install-recommends -y \
  ros-humble-image-transport \
  ros-humble-image-transport-plugins \
  ros-humble-point-cloud-transport \
  ros-humble-point-cloud-interfaces

