// generated from rosidl_generator_c/resource/idl.h.em
// with input from benchdraco_point_cloud_interfaces:msg/BenchCompressedPointCloud2.idl
// generated code does not contain a copyright notice

#ifndef BENCHDRACO_POINT_CLOUD_INTERFACES__MSG__BENCH_COMPRESSED_POINT_CLOUD2_H_
#define BENCHDRACO_POINT_CLOUD_INTERFACES__MSG__BENCH_COMPRESSED_POINT_CLOUD2_H_

#include "benchdraco_point_cloud_interfaces/msg/detail/bench_compressed_point_cloud2__struct.h"
#include "benchdraco_point_cloud_interfaces/msg/detail/bench_compressed_point_cloud2__functions.h"
#include "benchdraco_point_cloud_interfaces/msg/detail/bench_compressed_point_cloud2__type_support.h"

#endif  // BENCHDRACO_POINT_CLOUD_INTERFACES__MSG__BENCH_COMPRESSED_POINT_CLOUD2_H_
