---
encode_speed: 10
decode_speed: 7
encode_method: 0
deduplicate: true
force_quantization: true
quantization_POSITION: 5
quantization_NORMAL: 5
quantization_COLOR: 5
quantization_TEX_COORD: 5
quantization_GENERIC: 5
expert_quantization: false
expert_attribute_types: false
mapping_quantization_bits_x: 5
mapping_quantization_bits_y: 5
mapping_quantization_bits_z: 5
mapping_quantization_bits_rgb: 5
mapping_rgba_tweak_rgb: true
mapping_rgba_tweak_rgba: false
