---
encode_speed: 10
decode_speed: 7
encode_method: 0
deduplicate: true
force_quantization: true
quantization_POSITION: 14
quantization_NORMAL: 14
quantization_COLOR: 14
quantization_TEX_COORD: 14
quantization_GENERIC: 14
expert_quantization: false
expert_attribute_types: false
mapping_quantization_bits_x: 14
mapping_quantization_bits_y: 14
mapping_quantization_bits_z: 14
mapping_quantization_bits_rgb: 14
mapping_rgba_tweak_rgb: true
mapping_rgba_tweak_rgba: false
